### ISSUE TITLE
Death save not working

### ISSUE THREAD

**Issue by TPNils** [jopeek/fvtt-dndbeyond-character-sheet#18]
When you click on the Death save in the character sheet, it does not do anything, even when the character's HP is 0.

![image](https://user-images.githubusercontent.com/6439997/100484465-d9dd8f80-30fc-11eb-966e-62aa548bb509.png)

**Comment by jopeek** [comment]
Fixed in 1.5.2

**Comment by TPNils** [comment]
Thanks for fixing this! I am looking forward to introducing this sheet style for my players
