### ISSUE TITLE
Cannot open character sheets

### ISSUE THREAD

**Issue by drstevedillon** [jopeek/fvtt-dndbeyond-character-sheet#20]
https://media.discordapp.net/attachments/486930822465716249/785915250733481994/unknown.png?width=1215&height=77

Any characters that have this sheet as their default will not allow me to open the character sheet.

**Comment by jopeek** [comment]
Is this with the latest dnd5e system installed? And what version of FvTT?

**Comment by drstevedillon** [comment]
FVTT version 0.7.6I don't know if the 5e system is up to date... I didn't know systems got updated. I do not have any notifications to update the system. 

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 8, 2020 at 12:37 PM, Jan Ole Peek<notifications@github.com> wrote:   

Is this with the latest dnd5e system installed? And what version of FvTT?

**Comment by jopeek** [comment]
It looks like dnd5e isn’t at 1.1 or something. I will check mine later but they work fine for me. Check the game systems tab for an update.

**Comment by ROBORINE** [comment]
Had the same issue - updating the system does the trick! :)
