### ISSUE TITLE
Broken character sheet

### ISSUE THREAD

**Issue by Hellstromtech** [jopeek/fvtt-dndbeyond-character-sheet#25]
When using this character sheet I can no longer use Mrprimates dndbeyond importer, it does not import half the things and complains about the sheet.

Tried reinstalling importer, 5e system and this character sheet to no avail.

Everything works without problems on other character sheets.

**Comment by jopeek** [comment]
That doesn’t make much sense to me as the sheet is just a visual representation of the same data. But, I’m not familiar with the importer. Perhaps changing back to the default sheet, importing, and then back to mine, will work.

**Comment by Hellstromtech** [comment]
The error im getting is the following:

ReferenceError: An error occurred while rendering DNDBeyondCharacterSheet5e 113: DEFAULT_TOKEN is not defined
[Detected 3 packages: dndbeyond-character-sheet, system:dnd5e, lib-wrapper]

Your suggested solution does not work.

**Comment by jopeek** [comment]
This should be fixed by now.
