### ISSUE TITLE
Not able to open a Character Sheet

### ISSUE THREAD

**Issue by Chaosfea** [jopeek/fvtt-dndbeyond-character-sheet#26]
So since i updated the Character Sheet of one of my PCs through ddb Importer from MrPrimate (i updated other PCs as well with no issue), i can't open that Characters Sheet anymore. I tried with FindTheCulprit and found this module is seemingly the Cause of it. Disabling it enabled me to open the Sheet again. I even imported again after disabling the module/changing the sheet type and then turned it on again but nothing changed, still can't access it if i set the Sheet type to the ddb 5e sheet.

**Comment by jopeek** [comment]
This seems to be related to the importer you’re using. I don’t think I change any data on this sheet.

**Comment by Imp-ulse** [comment]
im having the exact same issue, it was fine before the last foundation update, only your character sheet if affected, the others i have still work fine (also use the D&D beyond importer) characters imported before the update, still open

**Comment by jopeek** [comment]
This should be fixed by now.
