### ISSUE TITLE
Double 'Action' tab when Character Actions List is installed

### ISSUE THREAD

**Issue by joevaughan** [jopeek/fvtt-dndbeyond-character-sheet#29]
Foundry Version(s): v9 and v10
DnDBeyond Character Sheet Version: latest (1.9.0) 

I run multiple character sheet modules (default, tidy5e, OGL, this) to give my players a choice of which they prefer so I run the Character Actions List module to give them an actions list on the default and other Character Sheets. 

I know this module/sheet has an action list built in however if the Character Actions List module is installed, there is a double 'actions' tab as per the image below. 

To be clear: has no functional (detrimental) effects as far asI can tell (you can click either actions tab and they work) but would be cleaner to either detect the Character Actions List module/tab and disable same or to properly integrate it as per @akrigline's request in issue #21 

<img width="887" alt="image" src="https://user-images.githubusercontent.com/92576588/188265306-c18ccfde-d444-4bf1-9311-17a6fe125aeb.png">

Edit: Should have said: Love the module and thanks for all your amazing work! :D

**Comment by akrigline** [comment]
Please note that the character actions list module is not marked ready for v10

**Comment by joevaughan** [comment]
> Please note that the character actions list module is not marked ready for v10

I'm aware. However does seem to be functioning (for me) with no problems that I've come across yet.

**Comment by brandon-hurler** [comment]
I am also experiencing this same issue. Are there plans to add the additional check here or is it work that Character Actions would need to take?

**Comment by jopeek** [comment]
Uh I can try to figure out if it’s something I can adjust. Will try.

**Comment by brandon-hurler** [comment]
Thank you for checking, I appreciate it!

**Comment by jopeek** [comment]
Resolved in 1.9.2
