### ISSUE TITLE
Issues with new dnd game update

### ISSUE THREAD

**Issue by hedgehog8711** [jopeek/fvtt-dndbeyond-character-sheet#30]
There was an update the the DND 5e game system update to 2.1.1. When I select this sheet as an option for my character the sheet does not display at all, and once it is set the only way to correct is to disable the module to force it back to the default sheet. Thank you in advance for your help. 

Thanks
Greg

**Comment by jopeek** [comment]
I am so tired of breaking dnd5e game system updates. Sigh.

I’ll get it fixed before the weekend when I need it for my own game. Thanks for the heads up!

Sent with Spark

**Comment by jopeek** [comment]
Fixed in 1.9.3
