### ISSUE TITLE
Abilities and Conditions Windows Truncation / Blank Space

### ISSUE THREAD

**Issue by zoonza** [jopeek/fvtt-dndbeyond-character-sheet#31]
The ability scores/conditions are truncated to a small window, leaving a large blank space to the right of it.

Also, ability names such as "Strength", "Constitution", and so on are missing (image attached).

![image](https://user-images.githubusercontent.com/67245746/212498667-7954f3a4-217c-427e-a931-d2ecd247c7df.png)

**Comment by jopeek** [comment]
Yup just realized that today. Will fix it tomorrow.

**Comment by jopeek** [comment]
This is fixed in 1.9.4, though my issue was not as severe as yours. I was missing headers but did not have this blank space. Your alignment is also all screwed up. Seems like an interfering module.

**Comment by zoonza** [comment]
Thank you! Looks like the interfering module was _5e-Custom Abilities & Skills_, in case anyone else has the same issue.
