### ISSUE TITLE
items are no longer clickable or editable after update

### ISSUE THREAD

**Issue by f4hy** [jopeek/fvtt-dndbeyond-character-sheet#33]
All items and features on the character sheet are no longer clickable for me after the update. Switching back to default sheet everything works again, and switching back to the beyond sheet and nothing can be used again. 
This is true for the gm user as well as players. 

I don't see any errors in the console. I'll try disabling other modules to see if it's some interaction.

**Comment by jopeek** [comment]
Huh that’s odd. I will check this evening. Maybe I screwed something up when I added the search boxes.

**Comment by toddfacemyer** [comment]
Same for me. Sheets from other modules are still working. I also created a fresh world with only this sheet enabled and I experienced the same thing.

Some things are clickable, such as the Inspiration toggle or text/number fields. I can't open menus using the "+ Add" buttons, though. I can still click-and-drag onto the sheet to add things that way.

**Comment by jopeek** [comment]
Pretty sure I know why this is happening. Just won’t get a chance to fix it for a couple hours yet.

**Comment by f4hy** [comment]
Ok good to know there will eventually be a fix. I wonder if I can just downgrade for now.

**Comment by jopeek** [comment]
Fixed in 11.230.5

**Comment by f4hy** [comment]
Awesome thanks. ya looks good now.
